### ISSUE TITLE
css not switching correctly from webring

### ISSUE THREAD

**Issue by Evan-Nishi** [hackclub/summer-scrapbook#103]
When clicking on another user from the webring, the css doesn't change for the other users's profile.  This is fixed upon page reload.  For some pages only portions of the css change, suggesting that the css from the other user does load.

### When clicking on user from webring: 
![image](https://user-images.githubusercontent.com/42789870/94871787-b00b3380-03ff-11eb-8770-4e53b46fd047.png)

### Upon refresh:
![image](https://user-images.githubusercontent.com/42789870/94871801-c0231300-03ff-11eb-84b9-83f093dd8ebf.png)

**Comment by sampoder** [comment]
from my experience it switches, but only after a couple of seconds

**Comment by Evan-Nishi** [comment]
Interesting, maybe it's due to extensions I have enabled.  It persists until reload for me.
