### ISSUE TITLE
Image attachments overflowing post grid

### ISSUE THREAD

**Issue by sampoder** [hackclub/summer-scrapbook#115]
<img width="1093" alt="Screenshot 2020-10-31 at 8 32 33 AM" src="https://user-images.githubusercontent.com/39828164/97766927-cc5fd480-1b53-11eb-872e-cbfdb8b9fbe3.png">
<img width="1068" alt="Screenshot 2020-10-31 at 8 32 24 AM" src="https://user-images.githubusercontent.com/39828164/97766936-d386e280-1b53-11eb-86b3-30f046e51f0b.png">
<img width="338" alt="Screenshot 2020-10-31 at 8 32 06 AM" src="https://user-images.githubusercontent.com/39828164/97766938-d550a600-1b53-11eb-8b89-3412e81dfb3c.png">
<img width="1260" alt="Screenshot 2020-10-31 at 8 31 51 AM" src="https://user-images.githubusercontent.com/39828164/97766939-d5e93c80-1b53-11eb-8fc5-416de8269ee5.png">

**Comment by sampoder** [comment]
my investigation tells me it is broken in #113 and #114 but not #112 so smth happened after #112 was merged

**Comment by sampoder** [comment]
the overlapping stuff is fixed in #116

**Comment by lachlanjc** [comment]
What browser is this? It looks fine for me

**Comment by lachlanjc** [comment]
Oh, so this is almost certainly a layout issue caused by Next adding nested divs to the grid. We probably need to give divs inside the attachment grid `max-width: 100%`

**Comment by sampoder** [comment]
getting issues on Chroma and Safari
