### ISSUE TITLE
Webring Images Positioning 

### ISSUE THREAD

**Issue by sampoder** [hackclub/summer-scrapbook#123]
Seems to be another causality of the switch to `next/image`

view: https://scrapbook.hackclub.com/ced/

<img width="1552" alt="Screenshot 2020-11-08 at 7 58 22 PM" src="https://user-images.githubusercontent.com/39828164/98464286-c37a9d00-21fc-11eb-9621-0a483f28f537.png">

**Comment by lachlanjc** [comment]
If you want to tackle this, that’d be great—should be entirely in the CSS file. Not sure I have time this week
