### ISSUE TITLE
Add endpoint for avatar source URLs

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/summer-scrapbook#124]
I love how you can do https://github.com/lachlanjc.png to get any user avatar. Would be awesome to implement our own system like that for Hack Clubbers using Scrapbook. Could use a rewrite to an API route to accomplish that same path extension (I think), or else just an API route like https://scrapbook.hackclub.com/api/avatar/lachlanjc.

(I’m not planning to build this, so please take this on if you’re interested!)

**Comment by MatthewStanciu** [comment]
this sounds easy. i think i can do this right now 👀

**Comment by MatthewStanciu** [comment]
nvm i dont feel like it
