### ISSUE TITLE
Calendar grid on scrapbook which shows streak in green fades away after a few seconds.

### ISSUE THREAD

**Issue by KishoreKaushal** [hackclub/summer-scrapbook#20]
The calendar grid on the scrapbook which shows the streak in green fades away after a few seconds.

**When the page is just loaded:**
![grid-before](https://user-images.githubusercontent.com/21371609/85554414-80030600-b642-11ea-8a74-ab1e6d047607.png)

**Few seconds after the page is loaded:**
![grid-after](https://user-images.githubusercontent.com/21371609/85554425-842f2380-b642-11ea-8689-c2dadf4f9b6b.png)

**Comment by sampoder** [comment]
i'll have a go at fixing this

**Comment by sampoder** [comment]
https://github.com/kevinsqi/react-calendar-heatmap/issues/131#issuecomment-633073953

Seems the latest version of this is broken though this isn't very specific so i don't know, still searching around

**Comment by sampoder** [comment]
no luck so far :(

**Comment by lachlanjc** [comment]
This was fixed by #32 today! Thanks for the report.
