### ISSUE TITLE
Scrapbook doesn't show things enclosed in ticks (`). for eg. `ThisKindOfThing`

### ISSUE THREAD

**Issue by KishoreKaushal** [hackclub/summer-scrapbook#21]
**This was the text from the scrapbook slack channel.**

![newIssue](https://user-images.githubusercontent.com/21371609/85554864-f7389a00-b642-11ea-8959-1ba1e6d53b3b.png)

**And this is the preview that it shows on the scrapbook page.**

![Screenshot from 2020-06-24 17-46-34](https://user-images.githubusercontent.com/21371609/85554991-146d6880-b643-11ea-8358-b474d95a98af.png)

**Comment by lachlanjc** [comment]
![A208F4BF-91B9-45A4-9E6A-D1FBECF74F02](https://user-images.githubusercontent.com/5074763/86261202-407d7200-bb8c-11ea-80c5-bab8c6a10697.jpeg)
Looks like this got fixed alongside autolinking the other day. Thanks!
