### ISSUE TITLE
Cap Streaks at 7+

### ISSUE THREAD

**Issue by sampoder** [hackclub/summer-scrapbook#22]
Context Message from Zach: https://hackclub.slack.com/archives/G012QMUFP7W/p1592929659034500

Do we want to do the same for the main site?

If so I'll make a PR

**Comment by lachlanjc** [comment]
Yeah, go for it! You’ll need to do this on both the padge on the post component as well as the header of the profile page.

**Comment by lachlanjc** [comment]
@sampoder Are you working on this? I can definitely do it if you're not

**Comment by sampoder** [comment]
Oops, I'll work on it today shouldn't be too much

**Comment by lachlanjc** [comment]
This is now done via #25 & #27!
