### ISSUE TITLE
Links with spaces don't appear to be rendering

### ISSUE THREAD

**Issue by cjdenio** [hackclub/summer-scrapbook#38]
My scrapbook:

![image](https://user-images.githubusercontent.com/34525547/86517036-a91a5800-bdf3-11ea-9e86-3265e2862c75.png)
Slack:

![image](https://user-images.githubusercontent.com/34525547/86517039-b0416600-bdf3-11ea-83b7-7ce614270574.png)

**Comment by sampoder** [comment]
thank u!
