### ISSUE TITLE
I lost my streak, but my scrapbook still says I have a 1 day streak

### ISSUE THREAD

**Issue by zachlatta** [hackclub/summer-scrapbook#44]
![20200707_11h28m52s_grim](https://user-images.githubusercontent.com/992248/86804765-33a5c600-c045-11ea-8aa7-1646074e804b.png)
![20200707_11h30m49s_grim](https://user-images.githubusercontent.com/992248/86804874-52a45800-c045-11ea-8dd5-e81bc634f9da.png)

**Comment by lachlanjc** [comment]
This was fixed yesterday :+1:
