### ISSUE TITLE
Streak text overflow and (potentially) GitHub chart calculation issue

### ISSUE THREAD

**Issue by zachlatta** [hackclub/summer-scrapbook#53]
See below screenshot:

![8BBF63D6-AD52-4BD9-B7A3-7FF5AD65611C](https://user-images.githubusercontent.com/992248/86992123-c8581300-c16e-11ea-9bf1-ee46ae08c0fb.png)

Profile link is https://scrapbook.hackclub.com/jasonaa.

Notice streak text overflowing. I’m not sure if it’s a front end or backend issue (like the streak is higher than it actually should be), but also notice how the GitHub chart doesn’t line up with the streak.

**Comment by sampoder** [comment]
@lachlanjc said this being fixed in #36
