### ISSUE TITLE
Double space in social card

### ISSUE THREAD

**Issue by zachlatta** [hackclub/summer-scrapbook#54]
Not sure if this is an issue with the social card generation or with the app I’m using that’s rendering the social text, but it looks like there’s a double space in the meta description:

![AF206F64-6A16-4211-B93B-51A9AFC70760](https://user-images.githubusercontent.com/992248/86992287-2ab11380-c16f-11ea-8146-fcb14262b37d.jpeg)

**Comment by sampoder** [comment]
I'll fix this
