### ISSUE TITLE
Tooltip showing amount of "posts" in the activity grid

### ISSUE THREAD

**Issue by aljaxus** [hackclub/summer-scrapbook#60]
![image](https://user-images.githubusercontent.com/24414483/87171618-3584b900-c2d3-11ea-81e5-aba757d7c0f5.png)
When hovering over tiles where `posts-count >= 1`, a tooltip should appear showing the exact amount of posts. Somewhat like GH has, but without showing the date - that's not needed.

**Comment by lachlanjc** [comment]
Hmm. There is a `title` tooltip with this: https://github.com/hackclub/summer-scrapbook/blob/main/pages/%5Busername%5D.js#L125

Are you not seeing that? Or you’re thinking of a custom tooltip instead of just a `title`?

**Comment by aljaxus** [comment]
I know there's a title attribute, but it's not shown (using Firefox 78.0.2 on Win10 atm)

**Comment by sampoder** [comment]
@aljaxus feel free to correct me here, but I think you mean to add something like this when you hover

<img width="229" alt="Screenshot 2020-07-14 at 1 40 14 PM" src="https://user-images.githubusercontent.com/39828164/87388509-8d733680-c5d7-11ea-844f-23b6ade3e4b4.png">

**Comment by aljaxus** [comment]
> 
> 
> @aljaxus feel free to correct me here, but I think you mean to add something like this when you hover
> 
> <img alt="Screenshot 2020-07-14 at 1 40 14 PM" width="229" src="https://user-images.githubusercontent.com/39828164/87388509-8d733680-c5d7-11ea-844f-23b6ade3e4b4.png">

Yes, as mentioned in the initial message, something like GitHub would be nice - though I think that the date isn't really needed.

**Comment by lachlanjc** [comment]
Appreciate the idea, but not planning to add this. I think I’ve only seen 5+ posts in one day once ever, & otherwise the colors’ value scale is there to communicate. You’re more than welcome to use the post grid or the API to explore further
