### ISSUE TITLE
Hovering over a emoji has a weird border

### ISSUE THREAD

**Issue by sampoder** [hackclub/summer-scrapbook#75]
<img width="319" alt="Screenshot 2020-07-10 at 11 27 22 PM" src="https://user-images.githubusercontent.com/39828164/87388639-c8756a00-c5d7-11ea-83f4-5f514ceb1f3d.png">

**Comment by lachlanjc** [comment]
As mentioned in the PR, this is intentional. The white backgrounds are from low-quality emojis, & they have the same problem in the Slack app. The emojis will update if they're changed on the Slack end, so I'm fine with that.
