### ISSUE TITLE
Posts that start with a : appear on the website as a parrot emoji

### ISSUE THREAD

**Issue by MatthewStanciu** [hackclub/summer-scrapbook#86]
![IMG_0422](https://user-images.githubusercontent.com/14811170/89103774-5deb6900-d3e2-11ea-93ea-a3f66b8ec505.png)
From Jess Ding’s latest post.

![IMG_0421](https://user-images.githubusercontent.com/14811170/89103779-680d6780-d3e2-11ea-96b1-7972a77098fc.png)
This doesn’t happen if I move the :000

**Comment by lachlanjc** [comment]
Yep, that’s expected behavior, since it’s matching an emoji but can’t find a custom emoji image for the text of the post. The parrot is the fallback emoji. I guess we could look at fixing the regex, but last time we tried it stumped Zach & me

**Comment by MatthewStanciu** [comment]
This feels broken though, even if it is expected behavior. It’s not urgent but we should see if we can figure out the regex so that this doesn’t happen

**Comment by alchzh** [comment]
@lachlanjc `/^:[^ .,;`\u2013~!@#$%^&*(){}=\\:"<>?|A-Z]+:$/` should match a valid emoji specifier
