### ISSUE TITLE
Broken "About" link in nav

### ISSUE THREAD

**Issue by alchzh** [hackclub/summer-scrapbook#98]
Something about upgrading to Next.js 9.5 seems to have broken the `/about` link in nav. I found that changing the link to `/about/` appeared to fix this, but I'm worried that something else about route handling broke with 9.5 (and the two experimental features that were stabilized)

Leaving open for further investigation.

**Comment by alchzh** [comment]
yeah, all emoji seem to be broken as well. it seems even the API is being converted to trailing slashes leading to the rewrite failing

**Comment by alchzh** [comment]
Hmm I guess the emoji parsing was unrelated. The about link is still broken though

**Comment by lachlanjc** [comment]
Hmm, the about link works fine for me, both directly & clicking in the nav. https://scrapbook.hackclub.com/about/

**Comment by alchzh** [comment]
![bEd0RtFrlW](https://user-images.githubusercontent.com/8976828/93009460-8624c680-f54f-11ea-9854-4f5f0d1b867a.gif)

**Comment by alchzh** [comment]
![NfOAQ9Bd4P](https://user-images.githubusercontent.com/8976828/93009477-abb1d000-f54f-11ea-8dda-5e144be22bc9.gif)

**Comment by sampoder** [comment]
:+1: the About link doesn't work in nav for me as well

**Comment by sampoder** [comment]
the issue seems to have disappeared 🎉
